# Generated by Django 3.2 on 2022-09-28 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(max_length=100)),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainers')),
            ],
        ),
    ]
