# Generated by Django 3.2 on 2022-09-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='sport_image',
            field=models.ImageField(default='placeholder', upload_to=''),
        ),
    ]
