# Generated by Django 3.2 on 2022-09-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('featured_image', models.ImageField(default='blog_placeholder', upload_to='')),
                ('excerpt', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainers')),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to='profiles.UserProfile')),
            ],
        ),
    ]
